import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    appScreenContent: {
        padding: 0,
        paddingBottom: 0,
        paddingTop: 0,
        paddingLeft: 0,
        paddingRight: 0,
        paddingHorizontal: 0,
        maxWidth: '100%',
    },
    container: {
        flex: 1,
    },
    map: {
        flex: 1,
    },
    calloutContainer: {
        width: 200,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
    },
    androidPreviewCard: {
        position: 'absolute',
        left: 16,
        right: 16,
        bottom: 88,
        width: undefined,
        maxWidth: 420,
        alignSelf: 'center',
        elevation: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    loadingContainer: {
        position: 'absolute',
        bottom: 100,
        alignSelf: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
        padding: 12,
        borderRadius: 50,
    },
    filtersButton: {
        position: 'absolute',
        bottom: 24,
        left: 16,
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    filterBadge: {
        position: 'absolute',
        top: -2,
        right: -2,
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 3,
    },
    myLocationButton: {
        position: 'absolute',
        bottom: 24,
        right: 16,
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
});
